// GENERATED by worker/scripts/gen-services-index.mjs — do not edit by hand.
// Curated replacement for server/src/services/index.ts in the Worker bundle.

// Lazy: constructing a service (`fooService(db)`) succeeds and returns a proxy;
// the first property access or call on it throws. Route factories build their
// services eagerly, so an eager throw would take every route down.
function unavailable(name: string): any {
  const fail = (): never => { throw new Error(`${name} is not available on the Cloudflare Worker yet`); };
  const proxy: any = new Proxy(fail, {
    apply: () => proxy,
    construct: () => proxy,
    get: (_t, prop) => (prop === "then" ? undefined : fail()),
  });
  return proxy;
}

export { assetService } from "../../src/services/assets.js";
export { logActivity } from "../../src/services/activity-log.js";
export { publishActivity } from "../../src/services/activity-log.js";
export type { ActivityPublication } from "../../src/services/activity-log.js";
export { documentAnnotationService } from "../../src/services/document-annotations.js";
export { decisionTrainingService } from "../../src/services/decision-training.js";
export { folderService } from "../../src/services/folders.js";
export { accessService } from "../../src/services/access.js";
export { inboxAgentPolicyService } from "../../src/services/inbox-agent-policy.js";
export { inboxDismissalService } from "../../src/services/inbox-dismissals.js";
export const heartbeatService = unavailable("heartbeatService") as unknown as typeof import("../../src/services/heartbeat.js").heartbeatService;
export const issueService = unavailable("issueService") as unknown as typeof import("../../src/services/issues.js").issueService;
export { issueTreeControlService } from "../../src/services/issue-tree-control.js";
export { resourceMembershipService } from "../../src/services/resource-memberships.js";
export { sidebarPreferenceService } from "../../src/services/sidebar-preferences.js";
export const smokeLabService = unavailable("smokeLabService") as unknown as typeof import("../../src/services/smoke-lab.js").smokeLabService;
export { instanceSettingsService } from "../../src/services/instance-settings.js";
export const statusCardService = unavailable("statusCardService") as unknown as typeof import("../../src/services/status-cards.js").statusCardService;
export { budgetService } from "../../src/services/budgets.js";
export { costService } from "../../src/services/costs.js";
export { financeService } from "../../src/services/finance.js";
export const companyService = unavailable("companyService") as unknown as typeof import("../../src/services/companies.js").companyService;
export const agentService = unavailable("agentService") as unknown as typeof import("../../src/services/agents.js").agentService;
export { buildExportFidelityReport } from "../../src/services/export-fidelity.js";
export { collectExportFidelityCounts } from "../../src/services/export-fidelity.js";
export { companyArtifactsService } from "../../src/services/company-artifacts.js";
export const companyPortabilityService = unavailable("companyPortabilityService") as unknown as typeof import("../../src/services/company-portability.js").companyPortabilityService;
export const feedbackService = unavailable("feedbackService") as unknown as typeof import("../../src/services/feedback.js").feedbackService;
export { workTimelineService } from "../../src/services/work-timeline.js";
export { goalService } from "../../src/services/goals.js";
export const routineService = unavailable("routineService") as unknown as typeof import("../../src/services/routines.js").routineService;
export const approvalService = unavailable("approvalService") as unknown as typeof import("../../src/services/approvals.js").approvalService;
export { issueApprovalService } from "../../src/services/issue-approvals.js";
export const secretService = unavailable("secretService") as unknown as typeof import("../../src/services/secrets.js").secretService;
