// GENERATED by worker/scripts/gen-services-index.mjs — do not edit by hand.
// Curated replacement for server/src/services/index.ts in the Worker bundle.

// Lazy stub. Route factories build services eagerly and read properties off
// them (`heartbeatService(db).wakeup`), so construction and property access
// return proxies; the first call, await, string conversion, or JSON
// serialization of the result throws.
function unavailable(name: string): any {
  const fail = (): never => { throw new Error(`${name} is not available on the Cloudflare Worker yet`); };
  const child: any = new Proxy(fail, {
    apply: fail,
    construct: fail,
    get: (_t, prop) => (prop === "then" || prop === "toJSON" || prop === Symbol.toPrimitive || prop === "toString" || prop === "valueOf" ? fail() : child),
  });
  return new Proxy(fail, { apply: () => child, construct: () => child, get: (_t, prop) => (prop === "then" ? undefined : child) });
}

export { folderService } from "../../src/services/folders.js";
export { logActivity } from "../../src/services/activity-log.js";
export { goalService } from "../../src/services/goals.js";
export { inboxDismissalService } from "../../src/services/inbox-dismissals.js";
export { accessService } from "../../src/services/access.js";
export { inboxAgentPolicyService } from "../../src/services/inbox-agent-policy.js";
export { sidebarPreferenceService } from "../../src/services/sidebar-preferences.js";
export { resourceMembershipService } from "../../src/services/resource-memberships.js";
export { decisionTrainingService } from "../../src/services/decision-training.js";
export const heartbeatService = unavailable("heartbeatService") as unknown as typeof import("../../src/services/heartbeat.js").heartbeatService;
export { issueService } from "../../src/services/issues.js";
export { issueTreeControlService } from "../../src/services/issue-tree-control.js";
export { instanceSettingsService } from "../../src/services/instance-settings.js";
export { publishActivity } from "../../src/services/activity-log.js";
export type { ActivityPublication } from "../../src/services/activity-log.js";
export { budgetService } from "../../src/services/budgets.js";
export { costService } from "../../src/services/costs.js";
export { financeService } from "../../src/services/finance.js";
export { companyService } from "../../src/services/companies.js";
export { agentService } from "../../src/services/agents.js";
export { buildExportFidelityReport } from "../../src/services/export-fidelity.js";
export { collectExportFidelityCounts } from "../../src/services/export-fidelity.js";
export { companyArtifactsService } from "../../src/services/company-artifacts.js";
export const companyPortabilityService = unavailable("companyPortabilityService") as unknown as typeof import("../../src/services/company-portability.js").companyPortabilityService;
export const feedbackService = unavailable("feedbackService") as unknown as typeof import("../../src/services/feedback.js").feedbackService;
export { workTimelineService } from "../../src/services/work-timeline.js";
export { boardAuthService } from "../../src/services/board-auth.js";
export { deduplicateAgentName } from "../../src/services/agents.js";
export { notifyHireApproved } from "../../src/services/hire-hook.js";
export { projectService } from "../../src/services/projects.js";
export const workspaceOperationService = unavailable("workspaceOperationService") as unknown as typeof import("../../src/services/workspace-operations.js").workspaceOperationService;
export { agentInstructionsService } from "../../src/services/agent-instructions.js";
export { approvalService } from "../../src/services/approvals.js";
export const builtInAgentService = unavailable("builtInAgentService") as unknown as typeof import("../../src/services/built-in-agents.js").builtInAgentService;
export { companySkillService } from "../../src/services/company-skills.js";
export { ISSUE_LIST_DEFAULT_LIMIT } from "../../src/services/issues.js";
export { issueApprovalService } from "../../src/services/issue-approvals.js";
export { issueRecoveryActionService } from "../../src/services/issue-recovery-actions.js";
export { syncInstructionsBundleConfigFromFilePath } from "../../src/services/agent-instructions.js";
export { companySearchService } from "../../src/services/company-search.js";
export { executionWorkspaceService } from "../../src/services/execution-workspaces.js";
export { enrichWorkProductMetadataWithDiff } from "../../src/services/work-products.js";
export { issueThreadInteractionService } from "../../src/services/issue-thread-interactions.js";
export { ISSUE_LIST_MAX_LIMIT } from "../../src/services/issues.js";
export { issueReferenceService } from "../../src/services/issue-references.js";
export type { IssueFilters } from "../../src/services/issues.js";
export { clampIssueListLimit } from "../../src/services/issues.js";
export { documentService } from "../../src/services/documents.js";
export { documentAnnotationService } from "../../src/services/document-annotations.js";
export { routineService } from "../../src/services/routines.js";
export { workProductService } from "../../src/services/work-products.js";
export const secretService = unavailable("secretService") as unknown as typeof import("../../src/services/secrets.js").secretService;
export const statusCardService = unavailable("statusCardService") as unknown as typeof import("../../src/services/status-cards.js").statusCardService;
export { assetService } from "../../src/services/assets.js";
