// GENERATED by worker/scripts/gen-services-index.mjs — do not edit by hand.
// Curated replacement for server/src/services/index.ts in the Worker bundle.

function unavailable(name: string): never {
  throw new Error(`${name} is not available on the Cloudflare Worker yet`);
}

export { assetService } from "../../src/services/assets.js";
export { logActivity } from "../../src/services/activity-log.js";
export { publishActivity } from "../../src/services/activity-log.js";
export type { ActivityPublication } from "../../src/services/activity-log.js";
export { documentAnnotationService } from "../../src/services/document-annotations.js";
export { decisionTrainingService } from "../../src/services/decision-training.js";
export { folderService } from "../../src/services/folders.js";
export { accessService } from "../../src/services/access.js";
export { inboxAgentPolicyService } from "../../src/services/inbox-agent-policy.js";
export { inboxDismissalService } from "../../src/services/inbox-dismissals.js";
export const heartbeatService = ((..._args: unknown[]) => unavailable("heartbeatService")) as unknown as typeof import("../../src/services/heartbeat.js").heartbeatService;
export const issueService = ((..._args: unknown[]) => unavailable("issueService")) as unknown as typeof import("../../src/services/issues.js").issueService;
export { issueTreeControlService } from "../../src/services/issue-tree-control.js";
export { resourceMembershipService } from "../../src/services/resource-memberships.js";
export { sidebarPreferenceService } from "../../src/services/sidebar-preferences.js";
export const smokeLabService = ((..._args: unknown[]) => unavailable("smokeLabService")) as unknown as typeof import("../../src/services/smoke-lab.js").smokeLabService;
export { instanceSettingsService } from "../../src/services/instance-settings.js";
export const statusCardService = ((..._args: unknown[]) => unavailable("statusCardService")) as unknown as typeof import("../../src/services/status-cards.js").statusCardService;
export { budgetService } from "../../src/services/budgets.js";
export { costService } from "../../src/services/costs.js";
export { financeService } from "../../src/services/finance.js";
export const companyService = ((..._args: unknown[]) => unavailable("companyService")) as unknown as typeof import("../../src/services/companies.js").companyService;
export const agentService = ((..._args: unknown[]) => unavailable("agentService")) as unknown as typeof import("../../src/services/agents.js").agentService;
export { buildExportFidelityReport } from "../../src/services/export-fidelity.js";
export { collectExportFidelityCounts } from "../../src/services/export-fidelity.js";
export { companyArtifactsService } from "../../src/services/company-artifacts.js";
export const companyPortabilityService = ((..._args: unknown[]) => unavailable("companyPortabilityService")) as unknown as typeof import("../../src/services/company-portability.js").companyPortabilityService;
export const feedbackService = ((..._args: unknown[]) => unavailable("feedbackService")) as unknown as typeof import("../../src/services/feedback.js").feedbackService;
export { workTimelineService } from "../../src/services/work-timeline.js";
export { goalService } from "../../src/services/goals.js";
export const routineService = ((..._args: unknown[]) => unavailable("routineService")) as unknown as typeof import("../../src/services/routines.js").routineService;
export const approvalService = ((..._args: unknown[]) => unavailable("approvalService")) as unknown as typeof import("../../src/services/approvals.js").approvalService;
export { issueApprovalService } from "../../src/services/issue-approvals.js";
export const secretService = ((..._args: unknown[]) => unavailable("secretService")) as unknown as typeof import("../../src/services/secrets.js").secretService;
