// GENERATED by worker/scripts/gen-hub-stubs.mjs from server/src/adapters/registry.ts — do not edit.
// Every value export throws; the Worker cannot run this module.

// Lazy: calling/constructing returns a proxy; the first property access throws.
function unavailable(name: string): any {
  const fail = (): never => { throw new Error(`adapters/registry.${name} is not available on the Cloudflare Worker yet`); };
  const proxy: any = new Proxy(fail, { apply: () => proxy, construct: () => proxy, get: (_t, prop) => (prop === "then" ? undefined : fail()) });
  return proxy;
}

export const detectAdapterModel = unavailable("detectAdapterModel") as unknown as typeof import("../../../src/adapters/registry.js").detectAdapterModel;
export const findActiveServerAdapter = unavailable("findActiveServerAdapter") as unknown as typeof import("../../../src/adapters/registry.js").findActiveServerAdapter;
export const findServerAdapter = unavailable("findServerAdapter") as unknown as typeof import("../../../src/adapters/registry.js").findServerAdapter;
export const getPausedOverrides = unavailable("getPausedOverrides") as unknown as typeof import("../../../src/adapters/registry.js").getPausedOverrides;
export const getServerAdapter = unavailable("getServerAdapter") as unknown as typeof import("../../../src/adapters/registry.js").getServerAdapter;
export const isOverridePaused = unavailable("isOverridePaused") as unknown as typeof import("../../../src/adapters/registry.js").isOverridePaused;
export const listAdapterModels = unavailable("listAdapterModels") as unknown as typeof import("../../../src/adapters/registry.js").listAdapterModels;
export const listEnabledServerAdapters = unavailable("listEnabledServerAdapters") as unknown as typeof import("../../../src/adapters/registry.js").listEnabledServerAdapters;
export const listServerAdapters = unavailable("listServerAdapters") as unknown as typeof import("../../../src/adapters/registry.js").listServerAdapters;
export const refreshAdapterModels = unavailable("refreshAdapterModels") as unknown as typeof import("../../../src/adapters/registry.js").refreshAdapterModels;
export const registerServerAdapter = unavailable("registerServerAdapter") as unknown as typeof import("../../../src/adapters/registry.js").registerServerAdapter;
export const requireServerAdapter = unavailable("requireServerAdapter") as unknown as typeof import("../../../src/adapters/registry.js").requireServerAdapter;
export const resolveExternalAdapterRegistration = unavailable("resolveExternalAdapterRegistration") as unknown as typeof import("../../../src/adapters/registry.js").resolveExternalAdapterRegistration;
export const setOverridePaused = unavailable("setOverridePaused") as unknown as typeof import("../../../src/adapters/registry.js").setOverridePaused;
export const unregisterServerAdapter = unavailable("unregisterServerAdapter") as unknown as typeof import("../../../src/adapters/registry.js").unregisterServerAdapter;
export const waitForExternalAdapters = unavailable("waitForExternalAdapters") as unknown as typeof import("../../../src/adapters/registry.js").waitForExternalAdapters;
