// GENERATED by worker/scripts/gen-hub-stubs.mjs from server/src/adapters/index.ts — do not edit.
// Every value export throws; the Worker cannot run this module.

// Lazy: calling/constructing returns a proxy; the first property access throws.
function unavailable(name: string): any {
  const fail = (): never => { throw new Error(`adapters/index.${name} is not available on the Cloudflare Worker yet`); };
  const proxy: any = new Proxy(fail, { apply: () => proxy, construct: () => proxy, get: (_t, prop) => (prop === "then" ? undefined : fail()) });
  return proxy;
}

export const detectAdapterModel = unavailable("detectAdapterModel") as unknown as typeof import("../../../src/adapters/index.js").detectAdapterModel;
export const findActiveServerAdapter = unavailable("findActiveServerAdapter") as unknown as typeof import("../../../src/adapters/index.js").findActiveServerAdapter;
export const findServerAdapter = unavailable("findServerAdapter") as unknown as typeof import("../../../src/adapters/index.js").findServerAdapter;
export const getServerAdapter = unavailable("getServerAdapter") as unknown as typeof import("../../../src/adapters/index.js").getServerAdapter;
export const listAdapterModels = unavailable("listAdapterModels") as unknown as typeof import("../../../src/adapters/index.js").listAdapterModels;
export const listServerAdapters = unavailable("listServerAdapters") as unknown as typeof import("../../../src/adapters/index.js").listServerAdapters;
export const refreshAdapterModels = unavailable("refreshAdapterModels") as unknown as typeof import("../../../src/adapters/index.js").refreshAdapterModels;
export const registerServerAdapter = unavailable("registerServerAdapter") as unknown as typeof import("../../../src/adapters/index.js").registerServerAdapter;
export const requireServerAdapter = unavailable("requireServerAdapter") as unknown as typeof import("../../../src/adapters/index.js").requireServerAdapter;
export const runningProcesses = unavailable("runningProcesses") as unknown as typeof import("../../../src/adapters/index.js").runningProcesses;
export const unregisterServerAdapter = unavailable("unregisterServerAdapter") as unknown as typeof import("../../../src/adapters/index.js").unregisterServerAdapter;

export type { AcpTargetDescriptor, AdapterAgent, AdapterEnvironmentCheck, AdapterEnvironmentCheckLevel, AdapterEnvironmentTestContext, AdapterEnvironmentTestResult, AdapterEnvironmentTestStatus, AdapterExecutionContext, AdapterExecutionResult, AdapterInvocationMeta, AdapterRuntime, AdapterRuntimeEvent, AdapterRuntimeMcpAccess, AdapterRuntimeMcpServer, AdapterRuntimeToolAccess, AdapterRuntimeToolDelivery, AdapterSessionCodec, ServerAdapterModule, UsageSummary } from "../../../src/adapters/index.js";
