// GENERATED by worker/scripts/gen-hub-stubs.mjs from server/src/services/execution-workspaces.ts — do not edit.
// Every value export throws; the Worker cannot run this module.

// Lazy: calling/constructing returns a proxy; the first property access throws.
function unavailable(name: string): any {
  const fail = (): never => { throw new Error(`services/execution-workspaces.${name} is not available on the Cloudflare Worker yet`); };
  const proxy: any = new Proxy(fail, { apply: () => proxy, construct: () => proxy, get: (_t, prop) => (prop === "then" ? undefined : fail()) });
  return proxy;
}

export const EXECUTION_WORKSPACE_LIFECYCLE_GENERATION_METADATA_KEY = unavailable("EXECUTION_WORKSPACE_LIFECYCLE_GENERATION_METADATA_KEY") as unknown as typeof import("../../../src/services/execution-workspaces.js").EXECUTION_WORKSPACE_LIFECYCLE_GENERATION_METADATA_KEY;
export const EXECUTION_WORKSPACE_REOPEN_FAILED_REASON = unavailable("EXECUTION_WORKSPACE_REOPEN_FAILED_REASON") as unknown as typeof import("../../../src/services/execution-workspaces.js").EXECUTION_WORKSPACE_REOPEN_FAILED_REASON;
export const EXECUTION_WORKSPACE_REOPEN_PENDING_METADATA_KEY = unavailable("EXECUTION_WORKSPACE_REOPEN_PENDING_METADATA_KEY") as unknown as typeof import("../../../src/services/execution-workspaces.js").EXECUTION_WORKSPACE_REOPEN_PENDING_METADATA_KEY;
export const EXECUTION_WORKSPACE_REOPEN_PENDING_SINCE_METADATA_KEY = unavailable("EXECUTION_WORKSPACE_REOPEN_PENDING_SINCE_METADATA_KEY") as unknown as typeof import("../../../src/services/execution-workspaces.js").EXECUTION_WORKSPACE_REOPEN_PENDING_SINCE_METADATA_KEY;
export const ISSUE_TERMINAL_WORKSPACE_CLEANUP_REASON = unavailable("ISSUE_TERMINAL_WORKSPACE_CLEANUP_REASON") as unknown as typeof import("../../../src/services/execution-workspaces.js").ISSUE_TERMINAL_WORKSPACE_CLEANUP_REASON;
export const STALE_REOPEN_PENDING_CONSUMPTION_GRACE_MS = unavailable("STALE_REOPEN_PENDING_CONSUMPTION_GRACE_MS") as unknown as typeof import("../../../src/services/execution-workspaces.js").STALE_REOPEN_PENDING_CONSUMPTION_GRACE_MS;
export const bumpExecutionWorkspaceLifecycleGeneration = unavailable("bumpExecutionWorkspaceLifecycleGeneration") as unknown as typeof import("../../../src/services/execution-workspaces.js").bumpExecutionWorkspaceLifecycleGeneration;
export const clearMetadataReopenPendingConsumption = unavailable("clearMetadataReopenPendingConsumption") as unknown as typeof import("../../../src/services/execution-workspaces.js").clearMetadataReopenPendingConsumption;
export const deriveExecutionWorkspaceDeliveryState = unavailable("deriveExecutionWorkspaceDeliveryState") as unknown as typeof import("../../../src/services/execution-workspaces.js").deriveExecutionWorkspaceDeliveryState;
export const executionWorkspaceService = unavailable("executionWorkspaceService") as unknown as typeof import("../../../src/services/execution-workspaces.js").executionWorkspaceService;
export const mergeExecutionWorkspaceConfig = unavailable("mergeExecutionWorkspaceConfig") as unknown as typeof import("../../../src/services/execution-workspaces.js").mergeExecutionWorkspaceConfig;
export const metadataHasReopenPendingConsumption = unavailable("metadataHasReopenPendingConsumption") as unknown as typeof import("../../../src/services/execution-workspaces.js").metadataHasReopenPendingConsumption;
export const readExecutionWorkspaceConfig = unavailable("readExecutionWorkspaceConfig") as unknown as typeof import("../../../src/services/execution-workspaces.js").readExecutionWorkspaceConfig;
export const readExecutionWorkspaceLifecycleGeneration = unavailable("readExecutionWorkspaceLifecycleGeneration") as unknown as typeof import("../../../src/services/execution-workspaces.js").readExecutionWorkspaceLifecycleGeneration;
export const readMetadataReopenPendingConsumptionSince = unavailable("readMetadataReopenPendingConsumptionSince") as unknown as typeof import("../../../src/services/execution-workspaces.js").readMetadataReopenPendingConsumptionSince;
export const setMetadataReopenPendingConsumption = unavailable("setMetadataReopenPendingConsumption") as unknown as typeof import("../../../src/services/execution-workspaces.js").setMetadataReopenPendingConsumption;
export const toExecutionWorkspace = unavailable("toExecutionWorkspace") as unknown as typeof import("../../../src/services/execution-workspaces.js").toExecutionWorkspace;

export type { ExecutionWorkspaceBranchReconcileActor, ExecutionWorkspaceBranchReconcileInspection, ExecutionWorkspaceBranchReconcileMode, ExecutionWorkspaceBranchReconcileResult, ExecutionWorkspaceBranchRefResolution, ExecutionWorkspaceGitWorktreeContention, ExecutionWorkspaceServiceOptions, ReopenClosedIsolatedExecutionWorkspaceResult } from "../../../src/services/execution-workspaces.js";
