// GENERATED by worker/scripts/gen-hub-stubs.mjs from server/src/secrets/provider-registry.ts — do not edit.
// Every value export throws; the Worker cannot run this module.

// Lazy stub: construction and property access return proxies; the first call,
// await, string conversion, or JSON serialization of the result throws.
function unavailable(name: string): any {
  const fail = (): never => { throw new Error(`secrets/provider-registry.${name} is not available on the Cloudflare Worker yet`); };
  const child: any = new Proxy(fail, { apply: fail, construct: fail, get: (_t, prop) => (prop === "then" || prop === "toJSON" || prop === Symbol.toPrimitive || prop === "toString" || prop === "valueOf" ? fail() : child) });
  return new Proxy(fail, { apply: () => child, construct: () => child, get: (_t, prop) => (prop === "then" ? undefined : child) });
}

export const checkSecretProviders = unavailable("checkSecretProviders") as unknown as typeof import("../../../src/secrets/provider-registry.js").checkSecretProviders;
export const getSecretProvider = unavailable("getSecretProvider") as unknown as typeof import("../../../src/secrets/provider-registry.js").getSecretProvider;
export const listSecretProviders = unavailable("listSecretProviders") as unknown as typeof import("../../../src/secrets/provider-registry.js").listSecretProviders;
