// GENERATED by worker/scripts/gen-hub-stubs.mjs from server/src/secrets/provider-registry.ts — do not edit.
// Every value export throws; the Worker cannot run this module.

// Lazy: calling/constructing returns a proxy; the first property access throws.
function unavailable(name: string): any {
  const fail = (): never => { throw new Error(`secrets/provider-registry.${name} is not available on the Cloudflare Worker yet`); };
  const proxy: any = new Proxy(fail, { apply: () => proxy, construct: () => proxy, get: (_t, prop) => (prop === "then" ? undefined : fail()) });
  return proxy;
}

export const checkSecretProviders = unavailable("checkSecretProviders") as unknown as typeof import("../../../src/secrets/provider-registry.js").checkSecretProviders;
export const getSecretProvider = unavailable("getSecretProvider") as unknown as typeof import("../../../src/secrets/provider-registry.js").getSecretProvider;
export const listSecretProviders = unavailable("listSecretProviders") as unknown as typeof import("../../../src/secrets/provider-registry.js").listSecretProviders;
