// GENERATED by worker/scripts/gen-hub-stubs.mjs from server/src/services/smoke-lab.ts — do not edit.
// Every value export throws; the Worker cannot run this module.

// Lazy stub: construction and property access return proxies; the first call,
// await, string conversion, or JSON serialization of the result throws.
function unavailable(name: string): any {
  const fail = (): never => { throw new Error(`services/smoke-lab.${name} is not available on the Cloudflare Worker yet`); };
  const child: any = new Proxy(fail, { apply: fail, construct: fail, get: (_t, prop) => (prop === "then" || prop === "toJSON" || prop === Symbol.toPrimitive || prop === "toString" || prop === "valueOf" ? fail() : child) });
  return new Proxy(fail, { apply: () => child, construct: () => child, get: (_t, prop) => (prop === "then" ? undefined : child) });
}

export const SMOKE_LAB_BANNER = unavailable("SMOKE_LAB_BANNER") as unknown as typeof import("../../../src/services/smoke-lab.js").SMOKE_LAB_BANNER;
export const SMOKE_LAB_DEMO_EMAIL = unavailable("SMOKE_LAB_DEMO_EMAIL") as unknown as typeof import("../../../src/services/smoke-lab.js").SMOKE_LAB_DEMO_EMAIL;
export const SMOKE_LAB_DEMO_PASSWORD = unavailable("SMOKE_LAB_DEMO_PASSWORD") as unknown as typeof import("../../../src/services/smoke-lab.js").SMOKE_LAB_DEMO_PASSWORD;
export const SMOKE_LAB_OAUTH_CLIENT_ID = unavailable("SMOKE_LAB_OAUTH_CLIENT_ID") as unknown as typeof import("../../../src/services/smoke-lab.js").SMOKE_LAB_OAUTH_CLIENT_ID;
export const SMOKE_LAB_OAUTH_SCOPE = unavailable("SMOKE_LAB_OAUTH_SCOPE") as unknown as typeof import("../../../src/services/smoke-lab.js").SMOKE_LAB_OAUTH_SCOPE;
export const SMOKE_LAB_OAUTH_SCOPES = unavailable("SMOKE_LAB_OAUTH_SCOPES") as unknown as typeof import("../../../src/services/smoke-lab.js").SMOKE_LAB_OAUTH_SCOPES;
export const smokeLabService = unavailable("smokeLabService") as unknown as typeof import("../../../src/services/smoke-lab.js").smokeLabService;

export type { SmokeLabService } from "../../../src/services/smoke-lab.js";
