// GENERATED by worker/scripts/gen-hub-stubs.mjs from server/src/services/skills-catalog.ts — do not edit.
// Every value export throws; the Worker cannot run this module.

// Lazy stub: construction and property access return proxies; the first call,
// await, string conversion, or JSON serialization of the result throws.
function unavailable(name: string): any {
  const fail = (): never => { throw new Error(`services/skills-catalog.${name} is not available on the Cloudflare Worker yet`); };
  const child: any = new Proxy(fail, { apply: fail, construct: fail, get: (_t, prop) => (prop === "then" || prop === "toJSON" || prop === Symbol.toPrimitive || prop === "toString" || prop === "valueOf" ? fail() : child) });
  return new Proxy(fail, { apply: () => child, construct: () => child, get: (_t, prop) => (prop === "then" ? undefined : child) });
}

export const CatalogManifestUnavailableError = unavailable("CatalogManifestUnavailableError") as unknown as typeof import("../../../src/services/skills-catalog.js").CatalogManifestUnavailableError;
export const copyCatalogSkillFile = unavailable("copyCatalogSkillFile") as unknown as typeof import("../../../src/services/skills-catalog.js").copyCatalogSkillFile;
export const getCatalogPackageMetadata = unavailable("getCatalogPackageMetadata") as unknown as typeof import("../../../src/services/skills-catalog.js").getCatalogPackageMetadata;
export const getCatalogSkillOrThrow = unavailable("getCatalogSkillOrThrow") as unknown as typeof import("../../../src/services/skills-catalog.js").getCatalogSkillOrThrow;
export const isCatalogManifestUnavailableError = unavailable("isCatalogManifestUnavailableError") as unknown as typeof import("../../../src/services/skills-catalog.js").isCatalogManifestUnavailableError;
export const listCatalogSkills = unavailable("listCatalogSkills") as unknown as typeof import("../../../src/services/skills-catalog.js").listCatalogSkills;
export const listCatalogSkillsOrEmpty = unavailable("listCatalogSkillsOrEmpty") as unknown as typeof import("../../../src/services/skills-catalog.js").listCatalogSkillsOrEmpty;
export const readCatalogSkillFile = unavailable("readCatalogSkillFile") as unknown as typeof import("../../../src/services/skills-catalog.js").readCatalogSkillFile;
export const resolveCatalogSkillReference = unavailable("resolveCatalogSkillReference") as unknown as typeof import("../../../src/services/skills-catalog.js").resolveCatalogSkillReference;
