// GENERATED by worker/scripts/gen-hub-stubs.mjs from server/src/services/company-portability.ts — do not edit.
// Every value export throws; the Worker cannot run this module.

// Lazy stub: construction and property access return proxies; the first call,
// await, string conversion, or JSON serialization of the result throws.
function unavailable(name: string): any {
  const fail = (): never => { throw new Error(`services/company-portability.${name} is not available on the Cloudflare Worker yet`); };
  const child: any = new Proxy(fail, { apply: fail, construct: fail, get: (_t, prop) => (prop === "then" || prop === "toJSON" || prop === Symbol.toPrimitive || prop === "toString" || prop === "valueOf" ? fail() : child) });
  return new Proxy(fail, { apply: () => child, construct: () => child, get: (_t, prop) => (prop === "then" ? undefined : child) });
}

export const companyPortabilityService = unavailable("companyPortabilityService") as unknown as typeof import("../../../src/services/company-portability.js").companyPortabilityService;
export const dedupeImportedCompanyName = unavailable("dedupeImportedCompanyName") as unknown as typeof import("../../../src/services/company-portability.js").dedupeImportedCompanyName;
export const parseGitHubSourceUrl = unavailable("parseGitHubSourceUrl") as unknown as typeof import("../../../src/services/company-portability.js").parseGitHubSourceUrl;
export const renderFrontmatter = unavailable("renderFrontmatter") as unknown as typeof import("../../../src/services/company-portability.js").renderFrontmatter;
export const renderYamlBlock = unavailable("renderYamlBlock") as unknown as typeof import("../../../src/services/company-portability.js").renderYamlBlock;
export const rewriteEmbeddedAssetUrls = unavailable("rewriteEmbeddedAssetUrls") as unknown as typeof import("../../../src/services/company-portability.js").rewriteEmbeddedAssetUrls;
