// GENERATED by worker/scripts/gen-hub-stubs.mjs from server/src/services/secrets.ts — do not edit.
// Every value export throws; the Worker cannot run this module.

// Lazy: calling/constructing returns a proxy; the first property access throws.
function unavailable(name: string): any {
  const fail = (): never => { throw new Error(`services/secrets.${name} is not available on the Cloudflare Worker yet`); };
  const proxy: any = new Proxy(fail, { apply: () => proxy, construct: () => proxy, get: (_t, prop) => (prop === "then" ? undefined : fail()) });
  return proxy;
}

export const CLAUDE_LOCAL_ADAPTER_TYPE = unavailable("CLAUDE_LOCAL_ADAPTER_TYPE") as unknown as typeof import("../../../src/services/secrets.js").CLAUDE_LOCAL_ADAPTER_TYPE;
export const CLAUDE_OAUTH_CLAIM_REJECTED = unavailable("CLAUDE_OAUTH_CLAIM_REJECTED") as unknown as typeof import("../../../src/services/secrets.js").CLAUDE_OAUTH_CLAIM_REJECTED;
export const CLAUDE_OAUTH_CREDENTIAL_CONFLICT = unavailable("CLAUDE_OAUTH_CREDENTIAL_CONFLICT") as unknown as typeof import("../../../src/services/secrets.js").CLAUDE_OAUTH_CREDENTIAL_CONFLICT;
export const DEVICE_LOGIN_SECRET_CHECK_CONSUMER_ID = unavailable("DEVICE_LOGIN_SECRET_CHECK_CONSUMER_ID") as unknown as typeof import("../../../src/services/secrets.js").DEVICE_LOGIN_SECRET_CHECK_CONSUMER_ID;
export const SANDBOX_CLEANUP_CONSUMER_ID = unavailable("SANDBOX_CLEANUP_CONSUMER_ID") as unknown as typeof import("../../../src/services/secrets.js").SANDBOX_CLEANUP_CONSUMER_ID;
export const assertClaudeOAuthBindingInvariant = unavailable("assertClaudeOAuthBindingInvariant") as unknown as typeof import("../../../src/services/secrets.js").assertClaudeOAuthBindingInvariant;
export const claudeOAuthClaimRejectedError = unavailable("claudeOAuthClaimRejectedError") as unknown as typeof import("../../../src/services/secrets.js").claudeOAuthClaimRejectedError;
export const isFixedClaudeOAuthBinding = unavailable("isFixedClaudeOAuthBinding") as unknown as typeof import("../../../src/services/secrets.js").isFixedClaudeOAuthBinding;
export const normalizeSecretKey = unavailable("normalizeSecretKey") as unknown as typeof import("../../../src/services/secrets.js").normalizeSecretKey;
export const secretService = unavailable("secretService") as unknown as typeof import("../../../src/services/secrets.js").secretService;

export type { AgentSecretAccessEntry, AgentSecretReadContext, ClaudeOAuthBindingInvariantDecision, ClaudeOAuthBindingInvariantInput, ClaudeOAuthUserSecretResult, MissingRuntimeBinding, RuntimeSecretManifestEntry } from "../../../src/services/secrets.js";
