// GENERATED by worker/scripts/gen-hub-stubs.mjs from server/src/services/built-in-agents.ts — do not edit.
// Every value export throws; the Worker cannot run this module.

// Lazy stub: construction and property access return proxies; the first call,
// await, string conversion, or JSON serialization of the result throws.
function unavailable(name: string): any {
  const fail = (): never => { throw new Error(`services/built-in-agents.${name} is not available on the Cloudflare Worker yet`); };
  const child: any = new Proxy(fail, { apply: fail, construct: fail, get: (_t, prop) => (prop === "then" || prop === "toJSON" || prop === Symbol.toPrimitive || prop === "toString" || prop === "valueOf" ? fail() : child) });
  return new Proxy(fail, { apply: () => child, construct: () => child, get: (_t, prop) => (prop === "then" ? undefined : child) });
}

export const builtInAgentService = unavailable("builtInAgentService") as unknown as typeof import("../../../src/services/built-in-agents.js").builtInAgentService;
export const deriveBuiltInAgentStatus = unavailable("deriveBuiltInAgentStatus") as unknown as typeof import("../../../src/services/built-in-agents.js").deriveBuiltInAgentStatus;
export const getBuiltInAgentDefinition = unavailable("getBuiltInAgentDefinition") as unknown as typeof import("../../../src/services/built-in-agents.js").getBuiltInAgentDefinition;
export const listBuiltInAgentDefinitions = unavailable("listBuiltInAgentDefinitions") as unknown as typeof import("../../../src/services/built-in-agents.js").listBuiltInAgentDefinitions;
export const readBuiltInTextWithFallback = unavailable("readBuiltInTextWithFallback") as unknown as typeof import("../../../src/services/built-in-agents.js").readBuiltInTextWithFallback;
export const reconcileBuiltInAgentsOnStartup = unavailable("reconcileBuiltInAgentsOnStartup") as unknown as typeof import("../../../src/services/built-in-agents.js").reconcileBuiltInAgentsOnStartup;
export const requireBuiltInAgentDefinition = unavailable("requireBuiltInAgentDefinition") as unknown as typeof import("../../../src/services/built-in-agents.js").requireBuiltInAgentDefinition;
export const validateBuiltInAgentDefinitions = unavailable("validateBuiltInAgentDefinitions") as unknown as typeof import("../../../src/services/built-in-agents.js").validateBuiltInAgentDefinitions;

export type { BuiltInAgentBundleDefinition, BuiltInAgentDefinition, BuiltInAgentProvisionActor, BuiltInAgentProvisionInput, BuiltInAgentProvisionResult, BuiltInAgentState, BuiltInAgentStatus, BuiltInManagedResourceKind, BuiltInManagedResourceState, BuiltInManagedResourceStockStatus, RequiredBuiltInAgent, RequiredBuiltInAgentWarning } from "../../../src/services/built-in-agents.js";
