// GENERATED by worker/scripts/gen-hub-stubs.mjs from server/src/services/agents.ts — do not edit.
// Every value export throws; the Worker cannot run this module.

// Lazy: calling/constructing returns a proxy; the first property access throws.
function unavailable(name: string): any {
  const fail = (): never => { throw new Error(`services/agents.${name} is not available on the Cloudflare Worker yet`); };
  const proxy: any = new Proxy(fail, { apply: () => proxy, construct: () => proxy, get: (_t, prop) => (prop === "then" ? undefined : fail()) });
  return proxy;
}

export const agentService = unavailable("agentService") as unknown as typeof import("../../../src/services/agents.js").agentService;
export const deduplicateAgentName = unavailable("deduplicateAgentName") as unknown as typeof import("../../../src/services/agents.js").deduplicateAgentName;
export const hasAgentShortnameCollision = unavailable("hasAgentShortnameCollision") as unknown as typeof import("../../../src/services/agents.js").hasAgentShortnameCollision;
