// GENERATED by worker/scripts/gen-hub-stubs.mjs from server/src/services/routines.ts — do not edit.
// Every value export throws; the Worker cannot run this module.

// Lazy: calling/constructing returns a proxy; the first property access throws.
function unavailable(name: string): any {
  const fail = (): never => { throw new Error(`services/routines.${name} is not available on the Cloudflare Worker yet`); };
  const proxy: any = new Proxy(fail, { apply: () => proxy, construct: () => proxy, get: (_t, prop) => (prop === "then" ? undefined : fail()) });
  return proxy;
}

export const nextCronTickInTimeZone = unavailable("nextCronTickInTimeZone") as unknown as typeof import("../../../src/services/routines.js").nextCronTickInTimeZone;
export const routineService = unavailable("routineService") as unknown as typeof import("../../../src/services/routines.js").routineService;
export const routineWebhookUrl = unavailable("routineWebhookUrl") as unknown as typeof import("../../../src/services/routines.js").routineWebhookUrl;
