// GENERATED by worker/scripts/gen-hub-stubs.mjs from server/src/services/companies.ts — do not edit.
// Every value export throws; the Worker cannot run this module.

// Lazy: calling/constructing returns a proxy; the first property access throws.
function unavailable(name: string): any {
  const fail = (): never => { throw new Error(`services/companies.${name} is not available on the Cloudflare Worker yet`); };
  const proxy: any = new Proxy(fail, { apply: () => proxy, construct: () => proxy, get: (_t, prop) => (prop === "then" ? undefined : fail()) });
  return proxy;
}

export const companyService = unavailable("companyService") as unknown as typeof import("../../../src/services/companies.js").companyService;

export type { CompanyActivityActor } from "../../../src/services/companies.js";
