// GENERATED by worker/scripts/gen-hub-stubs.mjs from server/src/services/company-portability.ts — do not edit.
// Every value export throws; the Worker cannot run this module.

// Lazy: calling/constructing returns a proxy; the first property access throws.
function unavailable(name: string): any {
  const fail = (): never => { throw new Error(`services/company-portability.${name} is not available on the Cloudflare Worker yet`); };
  const proxy: any = new Proxy(fail, { apply: () => proxy, construct: () => proxy, get: (_t, prop) => (prop === "then" ? undefined : fail()) });
  return proxy;
}

export const companyPortabilityService = unavailable("companyPortabilityService") as unknown as typeof import("../../../src/services/company-portability.js").companyPortabilityService;
export const dedupeImportedCompanyName = unavailable("dedupeImportedCompanyName") as unknown as typeof import("../../../src/services/company-portability.js").dedupeImportedCompanyName;
export const parseGitHubSourceUrl = unavailable("parseGitHubSourceUrl") as unknown as typeof import("../../../src/services/company-portability.js").parseGitHubSourceUrl;
export const renderFrontmatter = unavailable("renderFrontmatter") as unknown as typeof import("../../../src/services/company-portability.js").renderFrontmatter;
export const renderYamlBlock = unavailable("renderYamlBlock") as unknown as typeof import("../../../src/services/company-portability.js").renderYamlBlock;
export const rewriteEmbeddedAssetUrls = unavailable("rewriteEmbeddedAssetUrls") as unknown as typeof import("../../../src/services/company-portability.js").rewriteEmbeddedAssetUrls;
