// GENERATED by worker/scripts/gen-hub-stubs.mjs from server/src/services/issues.ts — do not edit.
// Every value export throws; the Worker cannot run this module.

// Lazy: calling/constructing returns a proxy; the first property access throws.
function unavailable(name: string): any {
  const fail = (): never => { throw new Error(`services/issues.${name} is not available on the Cloudflare Worker yet`); };
  const proxy: any = new Proxy(fail, { apply: () => proxy, construct: () => proxy, get: (_t, prop) => (prop === "then" ? undefined : fail()) });
  return proxy;
}

export const BLOCKER_ATTENTION_MAX_DEPTH = unavailable("BLOCKER_ATTENTION_MAX_DEPTH") as unknown as typeof import("../../../src/services/issues.js").BLOCKER_ATTENTION_MAX_DEPTH;
export const BLOCKER_ATTENTION_MAX_NODES = unavailable("BLOCKER_ATTENTION_MAX_NODES") as unknown as typeof import("../../../src/services/issues.js").BLOCKER_ATTENTION_MAX_NODES;
export const ISSUE_BLOCKER_DIAGNOSTICS_MAX_BLOCKERS = unavailable("ISSUE_BLOCKER_DIAGNOSTICS_MAX_BLOCKERS") as unknown as typeof import("../../../src/services/issues.js").ISSUE_BLOCKER_DIAGNOSTICS_MAX_BLOCKERS;
export const ISSUE_CREATE_IDEMPOTENCY_KEY_RETENTION_DAYS = unavailable("ISSUE_CREATE_IDEMPOTENCY_KEY_RETENTION_DAYS") as unknown as typeof import("../../../src/services/issues.js").ISSUE_CREATE_IDEMPOTENCY_KEY_RETENTION_DAYS;
export const ISSUE_LIST_DEFAULT_LIMIT = unavailable("ISSUE_LIST_DEFAULT_LIMIT") as unknown as typeof import("../../../src/services/issues.js").ISSUE_LIST_DEFAULT_LIMIT;
export const ISSUE_LIST_MAX_LIMIT = unavailable("ISSUE_LIST_MAX_LIMIT") as unknown as typeof import("../../../src/services/issues.js").ISSUE_LIST_MAX_LIMIT;
export const ISSUE_SUBTREE_DIAGNOSTICS_MAX_ACTIVITY_RECORDS_PER_NODE = unavailable("ISSUE_SUBTREE_DIAGNOSTICS_MAX_ACTIVITY_RECORDS_PER_NODE") as unknown as typeof import("../../../src/services/issues.js").ISSUE_SUBTREE_DIAGNOSTICS_MAX_ACTIVITY_RECORDS_PER_NODE;
export const ISSUE_SUBTREE_DIAGNOSTICS_MAX_BLOCKERS_PER_NODE = unavailable("ISSUE_SUBTREE_DIAGNOSTICS_MAX_BLOCKERS_PER_NODE") as unknown as typeof import("../../../src/services/issues.js").ISSUE_SUBTREE_DIAGNOSTICS_MAX_BLOCKERS_PER_NODE;
export const ISSUE_SUBTREE_DIAGNOSTICS_MAX_DEPTH = unavailable("ISSUE_SUBTREE_DIAGNOSTICS_MAX_DEPTH") as unknown as typeof import("../../../src/services/issues.js").ISSUE_SUBTREE_DIAGNOSTICS_MAX_DEPTH;
export const ISSUE_SUBTREE_DIAGNOSTICS_MAX_NODES = unavailable("ISSUE_SUBTREE_DIAGNOSTICS_MAX_NODES") as unknown as typeof import("../../../src/services/issues.js").ISSUE_SUBTREE_DIAGNOSTICS_MAX_NODES;
export const ISSUE_SUBTREE_DIAGNOSTICS_MAX_WAKE_REQUESTS_PER_NODE = unavailable("ISSUE_SUBTREE_DIAGNOSTICS_MAX_WAKE_REQUESTS_PER_NODE") as unknown as typeof import("../../../src/services/issues.js").ISSUE_SUBTREE_DIAGNOSTICS_MAX_WAKE_REQUESTS_PER_NODE;
export const ISSUE_WAKE_DIAGNOSTICS_LOOKBACK_DAYS = unavailable("ISSUE_WAKE_DIAGNOSTICS_LOOKBACK_DAYS") as unknown as typeof import("../../../src/services/issues.js").ISSUE_WAKE_DIAGNOSTICS_LOOKBACK_DAYS;
export const ISSUE_WAKE_DIAGNOSTICS_MAX_ACTIVITY_RECORDS = unavailable("ISSUE_WAKE_DIAGNOSTICS_MAX_ACTIVITY_RECORDS") as unknown as typeof import("../../../src/services/issues.js").ISSUE_WAKE_DIAGNOSTICS_MAX_ACTIVITY_RECORDS;
export const ISSUE_WAKE_DIAGNOSTICS_MAX_WAKE_REQUESTS = unavailable("ISSUE_WAKE_DIAGNOSTICS_MAX_WAKE_REQUESTS") as unknown as typeof import("../../../src/services/issues.js").ISSUE_WAKE_DIAGNOSTICS_MAX_WAKE_REQUESTS;
export const MAX_CHILD_ISSUES_CREATED_BY_HELPER = unavailable("MAX_CHILD_ISSUES_CREATED_BY_HELPER") as unknown as typeof import("../../../src/services/issues.js").MAX_CHILD_ISSUES_CREATED_BY_HELPER;
export const TERMINAL_HEARTBEAT_RUN_STATUSES = unavailable("TERMINAL_HEARTBEAT_RUN_STATUSES") as unknown as typeof import("../../../src/services/issues.js").TERMINAL_HEARTBEAT_RUN_STATUSES;
export const clampIssueListLimit = unavailable("clampIssueListLimit") as unknown as typeof import("../../../src/services/issues.js").clampIssueListLimit;
export const deriveIssueCommentRunLogAttribution = unavailable("deriveIssueCommentRunLogAttribution") as unknown as typeof import("../../../src/services/issues.js").deriveIssueCommentRunLogAttribution;
export const deriveIssueUserContext = unavailable("deriveIssueUserContext") as unknown as typeof import("../../../src/services/issues.js").deriveIssueUserContext;
export const executeIssuePostCommitActions = unavailable("executeIssuePostCommitActions") as unknown as typeof import("../../../src/services/issues.js").executeIssuePostCommitActions;
export const heartbeatRunIsTerminalOrMissing = unavailable("heartbeatRunIsTerminalOrMissing") as unknown as typeof import("../../../src/services/issues.js").heartbeatRunIsTerminalOrMissing;
export const issueService = unavailable("issueService") as unknown as typeof import("../../../src/services/issues.js").issueService;
export const listUnfinalizedExecutionWorkspaceIds = unavailable("listUnfinalizedExecutionWorkspaceIds") as unknown as typeof import("../../../src/services/issues.js").listUnfinalizedExecutionWorkspaceIds;
export const parseStatusFilter = unavailable("parseStatusFilter") as unknown as typeof import("../../../src/services/issues.js").parseStatusFilter;
export const readAcceptedPlanConfirmationTarget = unavailable("readAcceptedPlanConfirmationTarget") as unknown as typeof import("../../../src/services/issues.js").readAcceptedPlanConfirmationTarget;
export const runWorkspaceIsFinalized = unavailable("runWorkspaceIsFinalized") as unknown as typeof import("../../../src/services/issues.js").runWorkspaceIsFinalized;

export type { ChildIssueCompletionSummary, IssueDependencyReadiness, IssueFilters, IssuePostCommitAction } from "../../../src/services/issues.js";
