// GENERATED by worker/scripts/gen-hub-stubs.mjs from server/src/services/status-cards.ts — do not edit.
// Every value export throws; the Worker cannot run this module.

// Lazy stub: construction and property access return proxies; the first call,
// await, string conversion, or JSON serialization of the result throws.
function unavailable(name: string): any {
  const fail = (): never => { throw new Error(`services/status-cards.${name} is not available on the Cloudflare Worker yet`); };
  const child: any = new Proxy(fail, { apply: fail, construct: fail, get: (_t, prop) => (prop === "then" || prop === "toJSON" || prop === Symbol.toPrimitive || prop === "toString" || prop === "valueOf" ? fail() : child) });
  return new Proxy(fail, { apply: () => child, construct: () => child, get: (_t, prop) => (prop === "then" ? undefined : child) });
}

export const statusCardService = unavailable("statusCardService") as unknown as typeof import("../../../src/services/status-cards.js").statusCardService;
