// GENERATED by worker/scripts/gen-hub-stubs.mjs from server/src/storage/index.ts — do not edit.
// Every value export throws; the Worker cannot run this module.

// Lazy stub: construction and property access return proxies; the first call,
// await, string conversion, or JSON serialization of the result throws.
function unavailable(name: string): any {
  const fail = (): never => { throw new Error(`storage/index.${name} is not available on the Cloudflare Worker yet`); };
  const child: any = new Proxy(fail, { apply: fail, construct: fail, get: (_t, prop) => (prop === "then" || prop === "toJSON" || prop === Symbol.toPrimitive || prop === "toString" || prop === "valueOf" ? fail() : child) });
  return new Proxy(fail, { apply: () => child, construct: () => child, get: (_t, prop) => (prop === "then" ? undefined : child) });
}

export const createStorageServiceFromConfig = unavailable("createStorageServiceFromConfig") as unknown as typeof import("../../../src/storage/index.js").createStorageServiceFromConfig;
export const getStorageService = unavailable("getStorageService") as unknown as typeof import("../../../src/storage/index.js").getStorageService;

export type { PutFileResult, StorageService } from "../../../src/storage/index.js";
