// GENERATED by worker/scripts/gen-hub-stubs.mjs from server/src/storage/index.ts — do not edit.
// Every value export throws; the Worker cannot run this module.

// Lazy: calling/constructing returns a proxy; the first property access throws.
function unavailable(name: string): any {
  const fail = (): never => { throw new Error(`storage/index.${name} is not available on the Cloudflare Worker yet`); };
  const proxy: any = new Proxy(fail, { apply: () => proxy, construct: () => proxy, get: (_t, prop) => (prop === "then" ? undefined : fail()) });
  return proxy;
}

export const createStorageServiceFromConfig = unavailable("createStorageServiceFromConfig") as unknown as typeof import("../../../src/storage/index.js").createStorageServiceFromConfig;
export const getStorageService = unavailable("getStorageService") as unknown as typeof import("../../../src/storage/index.js").getStorageService;

export type { PutFileResult, StorageService } from "../../../src/storage/index.js";
