// GENERATED by worker/scripts/gen-hub-stubs.mjs from server/src/services/tool-gateway.ts — do not edit.
// Every value export throws; the Worker cannot run this module.

// Lazy: calling/constructing returns a proxy; the first property access throws.
function unavailable(name: string): any {
  const fail = (): never => { throw new Error(`services/tool-gateway.${name} is not available on the Cloudflare Worker yet`); };
  const proxy: any = new Proxy(fail, { apply: () => proxy, construct: () => proxy, get: (_t, prop) => (prop === "then" ? undefined : fail()) });
  return proxy;
}

export const ToolGatewayHttpError = unavailable("ToolGatewayHttpError") as unknown as typeof import("../../../src/services/tool-gateway.js").ToolGatewayHttpError;
export const createToolGatewayService = unavailable("createToolGatewayService") as unknown as typeof import("../../../src/services/tool-gateway.js").createToolGatewayService;
export const isConnectionGrantAudienceAllowed = unavailable("isConnectionGrantAudienceAllowed") as unknown as typeof import("../../../src/services/tool-gateway.js").isConnectionGrantAudienceAllowed;
export const resolveCredentialGrantKind = unavailable("resolveCredentialGrantKind") as unknown as typeof import("../../../src/services/tool-gateway.js").resolveCredentialGrantKind;

export type { ConnectedMcpGatewayMetadata, ToolGatewayDescriptor, ToolGatewayProviderType, ToolGatewayRuntimeSlot, ToolGatewayService, ToolGatewaySession } from "../../../src/services/tool-gateway.js";
