// Pre-bundle for the Cloudflare Worker.
//
// server/src is imported as is; nothing there is edited. This step bundles
// worker/index.ts with an esbuild plugin that replaces, at build time, the
// server modules the Worker cannot run with lazy stubs (same export names,
// throw on use), then hands the result to wrangler, which still applies
// nodejs_compat polyfills and uploads it.
//
// A server/src module is stubbed when any of these holds:
//   1. it is listed in STUB_FILES or lives under a STUB_DIRS prefix (execution
//      plane: runner, sandboxes, worktrees, plugin workers, terminals, …);
//   2. it imports a Node-only builtin at value level (node:fs, child_process,
//      net, dns, tls, http, http2, readline, worker_threads);
//   3. it does Node-only work at module load: `import.meta.url` or
//      `createRequire` in a top-level statement, or randomUUID()/randomBytes()
//      in a top-level statement (workerd forbids random values at global scope).
// Hand-written shims in worker/shims win over generated stubs (SHIM_FILES).
// Route modules (src/routes/*) are never stubbed: a Node-bound route must not
// be mounted; the build prints a warning when one matches.
//
// Usage (from server/): node worker/build.mjs
import * as esbuild from "esbuild";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, relative, resolve, sep } from "node:path";
import { exportsOf, stubSource } from "./scripts/lib/module-exports.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const serverDir = resolve(here, "..");
const srcDir = resolve(serverDir, "src") + sep;
const packagesDir = resolve(serverDir, "..", "packages") + sep;
const shim = (...p) => resolve(here, "shims", ...p);

/** Real source file (relative to server/src) → hand-written replacement. */
const SHIM_FILES = {
  "services/index.ts": shim("services-index.ts"), // curated barrel (generated by scripts/gen-services-index.mjs)
  "instrumentation.ts": shim("instrumentation.ts"),
  "version.ts": shim("version.ts"),
  "build-commit.ts": shim("build-commit.ts"),
  "build-version.ts": shim("build-version.ts"),
  "server-info.ts": shim("server-info.ts"),
  "services/workspace-readiness.ts": shim("workspace-readiness.ts"),
  "services/native-runtime/native-restart-recovery.ts": shim("native-restart-recovery.ts"),
  "dev-server-status.ts": shim("dev-server-status.ts"),
  "services/live-events.ts": shim("live-events.ts"), // forwards to the LiveEventsRoom Durable Object
  "services/adapter-plugin-store.ts": shim("adapter-plugin-store.ts"), // JSON file on disk → no external adapters
  "services/skills-catalog.ts": shim("skills-catalog.ts"), // manifest bundled from packages/skills-catalog/generated
  "adapters/plugin-loader.ts": shim("adapter-plugin-loader.ts"), // external adapters live on disk → none
};

/** Modules the Worker must not run even if rule 2/3 would not catch them.
 *  (adapters/registry.ts runs: it only assembles adapter metadata at load; the
 *  execution parts it references resolve to lazy stubs.) */
const STUB_FILES = new Set([
  "storage/index.ts", "secrets/provider-registry.ts",
  "services/execution-workspaces.ts", "services/tool-gateway.ts", "services/heartbeat.ts",
  "services/status-cards.ts", "services/secrets.ts",
  "services/feedback.ts", "services/smoke-lab.ts", "services/company-portability.ts",
  "services/skills-catalog.ts", "services/built-in-agents.ts", "services/workspace-operations.ts",
  "services/workspace-runtime.ts", "services/environment-runtime.ts", "services/device-login-service.ts",
]);
/** Modules that import a Node-only builtin but only call it lazily (never at
 *  module load or on the request paths that run on the Worker). Not stubbed. */
const ALLOW_FILES = new Set(["services/tool-access.ts", "services/provider-trace-store.ts", "services/company-skills.ts"]);
/** Mounted route modules whose Node imports are only used on paths that answer
 *  501 (agent ssh/terminal, adapter install, plugin install, access proxy). */
const LAZY_ROUTES = new Set(["routes/agents.ts", "routes/adapters.ts", "routes/access.ts", "routes/plugins.ts"]);
const STUB_DIRS = ["services/native-runtime/", "services/runtime-exposure/", "realtime/", "vendor/", "modules/active-run-watchdog/"];
/** Workspace packages get the same per-file rules (they are imported by server
 *  code); the execution-plane packages are stubbed wholesale. `shared` and `db`
 *  are pure and never stubbed. */
// The adapter packages themselves follow the per-file rules: their server
// entries build the ServerAdapterModule objects (type, models, capabilities)
// the registry lists, while execute/login/skills files import child_process
// and are stubbed lazily.
const PACKAGE_STUB_DIRS = ["paperclip-runner/", "adapter-utils/src/acpx-engine/"];
const PACKAGE_ALLOW_DIRS = ["shared/", "db/"];

const NODE_ONLY_IMPORT = /^import\s+(?!type\s)[^;]*?from\s+"node:(fs|child_process|net|dns|tls|http|http2|readline|worker_threads)(\/[^"]*)?"/m;
/** Third-party packages that only run on Node (and cannot even be bundled for
 *  workerd); a module importing one at value level is stubbed like rule 2. */
const NODE_ONLY_PACKAGE_IMPORT = /^import\s+(?!type\s)[^;]*?from\s+"(@cursor\/sdk|bun:sqlite|better-sqlite3|node-pty)(\/[^"]*)?"/m;
const TOP_LEVEL_NODE_WORK = /^(?:export\s+)?(?:const|let|var)\s[^\n]*(import\.meta\.url|createRequire\(|randomUUID\(|randomBytes\()/m;

const stubbed = [];
const paperclipStubs = {
  name: "paperclip-src-stubs",
  setup(build) {
    // Hand-written shims: swap the path.
    build.onResolve({ filter: /^\.\.?\// }, (args) => {
      if (!args.importer.startsWith(srcDir)) return null;
      const target = resolve(args.resolveDir, args.path).replace(/\.js$/, ".ts");
      const rel = relative(srcDir, target);
      return SHIM_FILES[rel] ? { path: SHIM_FILES[rel] } : null;
    });
    // Generated stubs: keep the path, replace the contents.
    build.onLoad({ filter: /\.ts$/ }, (args) => {
      if (args.path.startsWith(packagesDir)) {
        const prel = relative(packagesDir, args.path);
        if (PACKAGE_ALLOW_DIRS.some((d) => prel.startsWith(d))) return null;
        let why = null;
        if (PACKAGE_STUB_DIRS.some((d) => prel.startsWith(d))) why = "execution-plane package";
        else {
          const s = readFileSync(args.path, "utf8");
          if (NODE_ONLY_IMPORT.test(s)) why = "imports a Node-only builtin";
          else if (NODE_ONLY_PACKAGE_IMPORT.test(s)) why = "imports a Node-only package";
          else if (TOP_LEVEL_NODE_WORK.test(s)) why = "Node-only work at module load";
        }
        if (!why) return null;
        const { values, hasDefault, literals } = exportsOf(args.path);
        stubbed.push(`packages/${prel} (${why}, ${values.size} exports, ${literals.size} literal constants kept)`);
        return { contents: stubSource(`packages/${prel.replace(/\.ts$/, "")}`, [...values.keys()], hasDefault, literals), loader: "ts" };
      }
      if (!args.path.startsWith(srcDir)) return null;
      const rel = relative(srcDir, args.path);
      if (rel.startsWith("routes" + sep)) {
        const s = readFileSync(args.path, "utf8");
        if (!LAZY_ROUTES.has(rel) && (NODE_ONLY_IMPORT.test(s) || TOP_LEVEL_NODE_WORK.test(s))) console.warn(`[worker/build] route module is Node-bound and should not be mounted: src/${rel}`);
        return null;
      }
      let why = null;
      if (ALLOW_FILES.has(rel)) return null;
      if (STUB_FILES.has(rel)) why = "listed";
      else if (STUB_DIRS.some((d) => rel.startsWith(d))) why = "execution-plane directory";
      else {
        const s = readFileSync(args.path, "utf8");
        if (NODE_ONLY_IMPORT.test(s)) why = "imports a Node-only builtin";
        else if (NODE_ONLY_PACKAGE_IMPORT.test(s)) why = "imports a Node-only package";
        else if (TOP_LEVEL_NODE_WORK.test(s)) why = "Node-only work at module load";
      }
      if (!why) return null;
      const { values, hasDefault, literals } = exportsOf(args.path);
      stubbed.push(`${rel} (${why}, ${values.size} exports, ${literals.size} literal constants kept)`);
      return { contents: stubSource(`src/${rel.replace(/\.ts$/, "")}`, [...values.keys()], hasDefault, literals), loader: "ts" };
    });
  },
};

// Skill files for the bundled skills catalog (shims/skills-catalog.ts): the
// manifest lists every file with its sha256; pack the text/entrypoint files
// (assets are never previewed) so catalog reads answer from the bundle.
{
  const catalogRoot = resolve(packagesDir, "skills-catalog");
  const manifest = JSON.parse(readFileSync(resolve(catalogRoot, "generated", "catalog.json"), "utf8"));
  const packed = {};
  for (const skill of manifest.skills) {
    if (skill.source) continue; // fetched from GitHub at request time
    for (const file of skill.files) {
      if (file.kind === "asset") continue;
      packed[`${skill.path}/${file.path}`] = readFileSync(resolve(catalogRoot, skill.path, file.path)).toString("base64");
    }
  }
  mkdirSync(resolve(here, "dist"), { recursive: true });
  writeFileSync(resolve(here, "dist", "skills-catalog-files.json"), JSON.stringify(packed));
  console.log(`[worker/build] packed ${Object.keys(packed).length} skills-catalog files`);
}

await esbuild.build({
  entryPoints: [resolve(here, "index.ts")],
  outfile: resolve(here, "dist", "index.mjs"),
  bundle: true,
  format: "esm",
  platform: "browser",
  target: "es2022",
  conditions: ["workerd", "worker", "browser"],
  mainFields: ["browser", "module", "main"],
  sourcemap: true,
  logLevel: "warning",
  // Provided by the workerd runtime (nodejs_compat) and by wrangler's own
  // bundling pass; keep them out of this bundle.
  external: [
    "node:*", "cloudflare:*",
    // bare builtin specifiers used by some third-party packages
    "assert", "buffer", "events", "http", "http2", "https", "net", "os", "path", "stream", "stream/web", "string_decoder", "tls", "url", "util", "zlib", "crypto", "fs", "child_process", "worker_threads", "async_hooks", "dns", "readline", "process", "querystring", "timers", "timers/promises", "perf_hooks", "diagnostics_channel", "module", "v8", "vm", "tty", "constants",
  ],
  alias: {
    express: shim("express.ts"),
    multer: shim("multer.ts"),
    // routes/assets.ts: SVG sanitizing only; the Worker answers 501 for SVG uploads.
    jsdom: shim("jsdom.ts"),
    dompurify: shim("dompurify.ts"),
    "pino-http": shim("pino-http.ts"),
    "@paperclipai/db": shim("paperclip-db.ts"),
  },
  define: {
    // server/src/middleware/logger.ts reads this at module load; the
    // production branch never calls pino.transport (absent in the pino build
    // selected for Workers). A runtime var is not visible at module load.
    "process.env.NODE_ENV": JSON.stringify("production"),
    // Some modules (ours and third-party) evaluate `new URL(x, import.meta.url)`
    // at load; on workerd import.meta.url is empty and that throws before the
    // first request. A stable file URL keeps module load working; anything
    // that then touches the file system still fails on use.
    "import.meta.url": JSON.stringify("file:///paperclip/server/worker/index.ts"),
  },
  plugins: [paperclipStubs],
});

if (process.env.WORKER_BUILD_VERBOSE) for (const s of stubbed.sort()) console.log("stub:", s);
console.log(`[worker/build] stubbed ${stubbed.length} server modules`);
